### ISSUE TITLE
pdf_parser.php should be included into classmap since composer autoloader does not see it

### ISSUE THREAD

**Issue by stepanzarubin** [Setasign/FPDI-FPDF#1]

**Comment by JanSlabon** [comment]
Thanks for the report! Anyhow this is not a bug but the class is execluded from the class map to allow us to load another [parser class](https://www.setasign.com/products/fpdi-pdf-parser/details/) dynamically. The class is mapped in the separate parser. So if the autoloader of the separate parser exists it will load the class otherwise the default class will be loaded. For us this was the only way to allow us to switch the class dynamically to another one. But what problem do you have exactly? I guess this could only be a problem if your include_path is missing "." ? Is this your problem?

**Comment by stepanzarubin** [comment]
I am getting:

```
include(pdf_parser.php): failed to open stream: No such file or directory
```

**Comment by stepanzarubin** [comment]
The package stops working out of the box, this is the main problem.

**Comment by stepanzarubin** [comment]
I think this tell the story:

```
if (!class_exists('pdf_parser')) {
    require_once('pdf_parser.php');
}

/**
 * Class fpdi_pdf_parser
 */
class fpdi_pdf_parser extends pdf_parser
...
```

Composer autoloader does not see it, my framework does not see it (and it should not actually).
How should I fix it your understanding? Include pdf_parser manually whenever I need the whole package? Please advice.

**Comment by JanSlabon** [comment]
The file is part of the package and is located in the same directory as FPDI itself. So the require_once() call should find the file if you have not changed your include_path directive to something uncommon. Please check if the file exists and also check your include_path directive.

**Comment by stepanzarubin** [comment]
It does not get to include_path since after composer autoloader, my framework autoloader is called which is unable to find it.

What helped is changing class_exists to avoid autoload:
```
if (!class_exists('pdf_parser',false)) {
    require_once('pdf_parser.php');
}
```

**Comment by JanSlabon** [comment]
So your autoload implementation is somewhat strange as it seems to be triggering errors or handles situations for file/classes it shouldn't. We exactly build in this class_exits() including the autoload flag, to be able to load the other pdf_parser.php class (available as an commercial add-on) through its class map.

**Comment by stepanzarubin** [comment]
This is standard Yii Framework autoloader. I believe any other framework will not be able to find it until included explicitly via class map. In my case framework is also installed via composer.

Would be great if you can provide another package which will rely on composer only, most people do not need pdf parser flexibility. Thanks.

**Comment by JanSlabon** [comment]
An autoload implementation that tries to load a file without checking for its existance is a very strange for me. This would mean that it doesn't allow another autoload implementation to be triggered if it is registered afterwards. It is really very uncommon and we are not going to provide a special version for such a special autoload implementation. So you may simply create an empty file pdf_parser.php which is loaded by your autoload implementation. The default require_once() should be called then, because the class is still not loaded. Otherwise you may add the file manually to the [class map](http://www.yiiframework.com/doc-2.0/guide-concept-autoloading.html#class-map) of Yii.
